# https://learn.microsoft.com/en-gb/azure/aks/csi-secrets-store-identity-access
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "howtoaks.fullnameApi" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.csiSecretStore.clientID }}
    tenantId: {{ .Values.csiSecretStore.tenantId }}
    keyvaultName: {{ .Values.csiSecretStore.vaultName }}
    objects: {{ .Values.csiSecretStore.objects }}
