apiVersion: v1
kind: Service
metadata:
  name: {{ include "howtoaks.fullnameApi" . }}
  labels:
    {{- include "howtoaks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "howtoaks.selectorLabelsApi" . | nindent 4 }}
