apiVersion: v1
kind: Service
metadata:
  name: {{ include "howtoaks.fullnameFrontend" . }}
  labels:
    {{- include "howtoaks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "howtoaks.selectorLabelsFront" . | nindent 4 }}
