# https://learn.microsoft.com/en-gb/azure/aks/csi-secrets-store-identity-access
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "howtoaks.fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.csiSecretStore.clientID }}
    tenantId: {{ .Values.csiSecretStore.tenantId }}
    keyvaultName: {{ .Values.csiSecretStore.vaultName }}
    objects: |
      array:{{- if not .Values.csiSecretStore.objects }} []
      {{- else }}
      {{- range $i := .Values.csiSecretStore.objects }}
      - |
        objectName: {{ $i.objectName }}
        objectType: secret
        objectVersion: {{ $i.objectVersion }}
      {{- end }}
      {{- end }}
